resources:
- manager.yaml
patches:
- path: imagepullpolicy_patch.yaml
  target:
    kind: Deployment
    name: kairos-capi-controller-manager
images:
- name: controller
  newName: ghcr.io/kairos-io/kairos-capi
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
